version: '3.1'

services:
  springapp:
    image: dox2410/spring-boot-mongo:2
    #restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongodb
    - MONGO_DB_USERNAME=mymongo
    - MONGO_DB_PASSWORD=mymongo123
    ports:
      - 8090:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - eko  
    #deploy:  # This will be considered only in docker swarm.
     # replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mymongo
    - MONGO_INITDB_ROOT_PASSWORD=mymongo123
    volumes:
      - /tmp/mongodb:/data/db
    restart: always
    networks:
    - eko
    
volumes:
  mongodb:
    external: true
    
networks:
  eko-network:
    external: true
